version: "3.4"
services:
  weaviate:
    image: cr.weaviate.io/semitechnologies/weaviate:1.25.8
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "6060:6060"
    environment:
      QUERY_DEFAULTS_LIMIT: 20
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: "true"
      PERSISTENCE_DATA_PATH: "/var/lib/weaviate"
      DISABLE_TELEMETRY: "true"
      CLUSTER_HOSTNAME: "node1"
    volumes:
      - weaviate_data:/var/lib/weaviate
volumes:
  weaviate_data:
